apiVersion: v1
kind: Endpoints
metadata:
  name: node-exporter-per-node
  namespace: kube-system
subsets:
- addresses:
  - ip: 172.18.0.7  # k3s-master IP
  - ip: 172.18.0.8  # k3s-worker-1 IP
  - ip: 172.18.0.5  # k3s-worker-2 IP
  ports:
  - port: 9100
    name: http
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: node-exporter-per-node
  namespace: kube-system
spec:
  clusterIP: None
  ports:
  - port: 9100
    name: http
    targetPort: 9100
  selector:
    app.kubernetes.io/name: node-exporter