apiVersion: v1
kind: Namespace
metadata:
  name: workload-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-stress
  namespace: workload-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cpu-stress
  template:
    metadata:
      labels:
        app: cpu-stress
    spec:
      containers:
      - name: cpu-stress
        image: polinux/stress
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        command: ["stress"]
        args: ["--cpu", "2", "--timeout", "600s", "--vm", "1", "--vm-bytes", "256M"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pending-pod-test
  namespace: workload-test
spec:
  replicas: 10
  selector:
    matchLabels:
      app: pending-pod-test
  template:
    metadata:
      labels:
        app: pending-pod-test
    spec:
      containers:
      - name: pause
        image: k8s.gcr.io/pause:3.8
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "1000m"
            memory: "2Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: cpu-stress-service
  namespace: workload-test
spec:
  selector:
    app: cpu-stress
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP